### ISSUE TITLE
GetApplicationFromMarathon - smells

### ISSUE THREAD

**Issue by dddpaul** [alxndrzuev/marathon-cli#10]
https://github.com/alxndrzuev/marathon-cli/blob/e76ff0a1048e4077f4172030d95183745b097b4c/internal/application.go#L12

В го из-за некоей узости ООО используют такой приемчик.
Экспортируемую функции суют в пакет, marathon в нашем случае.
Имя файла не важно.

Тогда в потребителе делаешь `marathon.GetApplications()`.

**Comment by alxndrzuev** [comment]
Перенес в отдельный пакет `marathon`
